id: P009393
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:36:39.343791
source_metadata:
  id: bdr:W8LS16750
  title: གསང་དོན་རྣམ་འབྱེད་འཕྲུལ་གྱི་ལྡེ་མིག་དང་གསང་དོན་ས་བཅད།
  author: ''
  volumes:
    0b35669cef6947eebe90c9e7ea59406e:
      image_group_id: I8LS16771
      title: ''
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
