id: I3F229BAB
legacy_id: P009393
ocr_import_info:
  bdrc_scan_id: W8LS16750
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T09:54:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:32:45.381106+00:00'
last_modified: 2022-09-04 11:32:50.370053
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS16750
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS16750
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་དོན་རྣམ་འབྱེད་འཕྲུལ་གྱི་ལྡེ་མིག་དང་གསང་དོན་ས་བཅད།
  author: མཉམ་མེད་ཤེས་རབ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9224849844383194
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I8LS16771:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS16771
      total_pages: 50
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS16771.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9224849844383194
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
