id: I3F229BAB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T09:55:14+00:00'
last_modified: '2022-06-08T10:41:40.753042+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16750
  title: གསང་དོན་རྣམ་འབྱེད་འཕྲུལ་གྱི་ལྡེ་མིག་དང་གསང་དོན་ས་བཅད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    41CF:
      image_group_id: I8LS16771
      title: ''
      total_pages: 50
      order: 1
      base_file: 41CF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
